name: ussd_advanced
description: Runs USSD code directly in your application, supporting single and multi-session USSD calls.
version: 2.0.0
homepage: https://github.com/EddieKamau/ussd_advanced

environment:
  sdk: ">=2.17.0 <4.0.0" # ✅ Compatible avec Flutter 3.10+
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # ✅ Compatible Dart >=2.17.0

flutter:
  plugin:
    platforms:
      android:
        package: com.phan_tech.ussd_advanced
        pluginClass: UssdAdvancedPlugin
      ios:
        pluginClass: UssdAdvancedPlugin

  # Optional: if you provide an example app
  # assets:
  #   - assets/
